// <auto-generated />
using System;
using GuardaPelaCultura.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GuardaPelaCultura.Migrations
{
    [DbContext(typeof(GuardaPelaCulturaContext))]
    [Migration("20201210110655_EmentaMigration")]
    partial class EmentaMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GuardaPelaCultura.Models.Ementa", b =>
                {
                    b.Property<int>("EmentaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DescricaoEmenta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeEmenta")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<float>("PrecoEmenta")
                        .HasColumnType("real");

                    b.Property<int>("QuantidadeEmenta")
                        .HasColumnType("int");

                    b.Property<int>("RestaurantesId")
                        .HasColumnType("int");

                    b.HasKey("EmentaId");

                    b.HasIndex("RestaurantesId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("GuardaPelaCultura.Models.ReservasRestaurante", b =>
                {
                    b.Property<int>("ReservasRestauranteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeReserva")
                        .IsRequired()
                        .HasColumnType("nvarchar(80)")
                        .HasMaxLength(80);

                    b.Property<string>("NumeroPessoas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroTelefoneReserva")
                        .IsRequired()
                        .HasColumnType("nvarchar(9)")
                        .HasMaxLength(9);

                    b.Property<int>("RestaurantesId")
                        .HasColumnType("int");

                    b.Property<int?>("RestaurantesId")
                        .HasColumnType("int");

                    b.HasKey("ReservasRestauranteId");

                    b.HasIndex("RestaurantesId");

                    b.ToTable("ReservasRestaurante");
                });

            modelBuilder.Entity("GuardaPelaCultura.Models.ReservasTakeAway", b =>
                {
                    b.Property<int>("ReservasTakeAwayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(80)")
                        .HasMaxLength(80);

                    b.Property<string>("NomeRestaurante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroTelefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReservasTakeAwayId");

                    b.ToTable("ReservasTakeAway");
                });

            modelBuilder.Entity("GuardaPelaCultura.Models.Restaurantes", b =>
                {
                    b.Property<int>("RestaurantesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmailRestaurante")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HorarioRestaurante")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<string>("LocalizacaoRestaurante")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<int>("LugaresRestaurante")
                        .HasColumnType("int");

                    b.Property<int>("MesasRestaurante")
                        .HasColumnType("int");

                    b.Property<string>("NomeRestaurante")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<string>("NumeroTelefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(9)")
                        .HasMaxLength(9);

                    b.Property<string>("TextoDescritivoRestaurante")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.HasKey("RestaurantesId");

                    b.ToTable("Restaurantes");
                });

            modelBuilder.Entity("GuardaPelaCultura.Models.Ementa", b =>
                {
                    b.HasOne("GuardaPelaCultura.Models.Restaurantes", "Restaurantes")
                        .WithMany()
                        .HasForeignKey("RestaurantesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GuardaPelaCultura.Models.ReservasRestaurante", b =>
                {
                    b.HasOne("GuardaPelaCultura.Models.Restaurantes", "Restaurantes")
                        .WithMany()
                        .HasForeignKey("RestaurantesId");
                });
#pragma warning restore 612, 618
        }
    }
}
