// <auto-generated />
using System;
using GuardaPelaCultura.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GuardaPelaCultura.Migrations
{
    [DbContext(typeof(GuardaPelaCulturaContext))]
    [Migration("20210113205506_InicialMigration")]
    partial class InicialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GuardaPelaCultura.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmailCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("NifCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(80)")
                        .HasMaxLength(80);

                    b.Property<string>("NumeroTelefoneCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(14)")
                        .HasMaxLength(14);

                    b.HasKey("ClienteId");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("GuardaPelaCultura.Models.Ementa", b =>
                {
                    b.Property<int>("EmentaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DescricaoEmenta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeEmenta")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<float>("PrecoEmenta")
                        .HasColumnType("real");

                    b.Property<int>("QuantidadeEmenta")
                        .HasColumnType("int");

                    b.Property<int>("RestaurantesId")
                        .HasColumnType("int");

                    b.HasKey("EmentaId");

                    b.HasIndex("RestaurantesId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("GuardaPelaCultura.Models.Mesa", b =>
                {
                    b.Property<int>("MesaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("LugaresRestaurante")
                        .HasColumnType("int");

                    b.Property<int>("MesasRestaurante")
                        .HasColumnType("int");

                    b.Property<int>("RestaurantesId")
                        .HasColumnType("int");

                    b.HasKey("MesaId");

                    b.HasIndex("RestaurantesId");

                    b.ToTable("Mesa");
                });

            modelBuilder.Entity("GuardaPelaCultura.Models.ReservasRestaurante", b =>
                {
                    b.Property<int>("ReservasRestauranteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("DataReserva")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstadoReserva")
                        .HasColumnType("bit");

                    b.Property<int>("MesaId")
                        .HasColumnType("int");

                    b.Property<int>("NumeroPessoas")
                        .HasColumnType("int");

                    b.Property<string>("ObservacaoReserva")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RestaurantesId")
                        .HasColumnType("int");

                    b.HasKey("ReservasRestauranteId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("MesaId");

                    b.HasIndex("RestaurantesId");

                    b.ToTable("ReservasRestaurante");
                });

            modelBuilder.Entity("GuardaPelaCultura.Models.ReservasTakeAway", b =>
                {
                    b.Property<int>("ReservasTakeAwayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(80)")
                        .HasMaxLength(80);

                    b.Property<string>("NomeRestaurante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroTelefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObservacaoTakeAway")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReservasTakeAwayId");

                    b.ToTable("ReservasTakeAway");
                });

            modelBuilder.Entity("GuardaPelaCultura.Models.Restaurantes", b =>
                {
                    b.Property<int>("RestaurantesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmailRestaurante")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<int>("HoraAbertura")
                        .HasColumnType("int");

                    b.Property<int>("HoraFecho")
                        .HasColumnType("int");

                    b.Property<byte[]>("Imagem")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("Imagem1")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("Imagem2")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("Imagem3")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("LocalizacaoRestaurante")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("NomeRestaurante")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("NumeroTelefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(14)")
                        .HasMaxLength(14);

                    b.Property<string>("TextoDescritivoRestaurante")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.HasKey("RestaurantesId");

                    b.ToTable("Restaurantes");
                });

            modelBuilder.Entity("GuardaPelaCultura.Models.Ementa", b =>
                {
                    b.HasOne("GuardaPelaCultura.Models.Restaurantes", "Restaurantes")
                        .WithMany()
                        .HasForeignKey("RestaurantesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GuardaPelaCultura.Models.Mesa", b =>
                {
                    b.HasOne("GuardaPelaCultura.Models.Restaurantes", "Restaurantes")
                        .WithMany()
                        .HasForeignKey("RestaurantesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GuardaPelaCultura.Models.ReservasRestaurante", b =>
                {
                    b.HasOne("GuardaPelaCultura.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuardaPelaCultura.Models.Mesa", "Mesa")
                        .WithMany()
                        .HasForeignKey("MesaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuardaPelaCultura.Models.Restaurantes", "Restaurantes")
                        .WithMany()
                        .HasForeignKey("RestaurantesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
